"""The fixed disclosure block that begins every report."""
from __future__ import annotations

DISCLOSURE_TITLE = "Important: hypothetical backtested performance"


def disclosure_block(*, samples: str, costs: str, benchmark: str, worst_drawdown: str, n_trials: str,
                     generated: str) -> str:
    """Markdown block; every argument is a plain-language string filled in by the caller."""
    return "\n".join([
        f"> **{DISCLOSURE_TITLE}.** Every number in this report is a *simulation* of what the stated rules "
        "would have done on historical data. No money was traded. Simulated results have inherent "
        "limitations: they are produced with hindsight, cannot reflect real fills, taxes or the behaviour "
        "of a person following the rules through losses, and are known to overstate live results.",
        ">",
        f"> - **Costs modelled (results are net of these):** {costs}",
        f"> - **Sample period:** {samples}",
        f"> - **Benchmark shown alongside every strategy:** {benchmark}",
        f"> - **Worst drawdown in these results:** {worst_drawdown}",
        f"> - **Number of variants tried (trial ledger):** {n_trials}. The more variants tried, the more "
        "the best one is flattered by luck; see dsr_pbo.md for the correction.",
        "> - **Past performance does not indicate future results.** Nothing here is investment advice.",
        f"> - Generated by `scripts/run_backtests.py` (deterministic Python, no language model) on {generated}.",
        "",
    ])
